// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCw9drGRWrG1-xUC6JGC2LS28VB20SaFzc',
    appId: '1:195267222086:web:19cc0873a2ee2dc0af8847',
    messagingSenderId: '195267222086',
    projectId: 'closeworld-4b365',
    authDomain: 'closeworld-4b365.firebaseapp.com',
    databaseURL: 'https://closeworld-4b365-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'closeworld-4b365.appspot.com',
    measurementId: 'G-7391E8QP94',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAarU14p4JGQZVsfac_0ugXja1500G-VME',
    appId: '1:195267222086:android:a5c765e02e554436af8847',
    messagingSenderId: '195267222086',
    projectId: 'closeworld-4b365',
    databaseURL: 'https://closeworld-4b365-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'closeworld-4b365.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAC-jfDifu5tucJzW2tp9rKAtTB-433Fso',
    appId: '1:195267222086:ios:4417c8d0218fd545af8847',
    messagingSenderId: '195267222086',
    projectId: 'closeworld-4b365',
    databaseURL: 'https://closeworld-4b365-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'closeworld-4b365.appspot.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAC-jfDifu5tucJzW2tp9rKAtTB-433Fso',
    appId: '1:195267222086:ios:52d147b89d5b494daf8847',
    messagingSenderId: '195267222086',
    projectId: 'closeworld-4b365',
    databaseURL: 'https://closeworld-4b365-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'closeworld-4b365.appspot.com',
    iosBundleId: 'com.example.chatapp.RunnerTests',
  );
}
